Repository test-fullautomation/python-extensions-collection, pull requests merged in 2022-11, with the labels that each got.

#15 README rst 2 md converter added
  readme.rst2md.py
Labels: enhancement, 0.6.0

#18 Converted parts of the documentation from RST format to LaTeX format (to improve the layout).
  PythonExtensionsCollection/Comparison/CComparison.py
  PythonExtensionsCollection/File/CFile.py
  PythonExtensionsCollection/PythonExtensionsCollection.pdf
  PythonExtensionsCollection/String/CString.py
  PythonExtensionsCollection/Utils/CUtils.py
  PythonExtensionsCollection/version.py
  packagedoc/additional_docs/Description.rst
  packagedoc/additional_docs/Description.tex
  packagedoc/additional_docs/History.tex
  packagedoc/additional_docs/Introduction.rst
  packagedoc/additional_docs/Introduction.tex
  packagedoc/packagedoc_config.json
  pytest/String/test_CString.py
Labels: 0.6.0

#20 Update release_to_pypi.yml
  .github/workflows/release_to_pypi.yml
Labels: enhancement, 0.6.0

#21 Documentation maintenance
  PythonExtensionsCollection/PythonExtensionsCollection.pdf
  PythonExtensionsCollection/version.py
  README.md
  README.rst
  packagedoc/additional_docs/Description.tex
Labels: documentation, 0.6.0

#22 Documentation adapted to GenPackageDoc v. 0.36.0
  PythonExtensionsCollection/PythonExtensionsCollection.pdf
  PythonExtensionsCollection/version.py
  packagedoc/additional_docs/Description.tex
  packagedoc/additional_docs/History.tex
  packagedoc/packagedoc_config.json
Labels: 0.6.0
